services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rabbitmq:
    image: rabbitmq:3.8
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    hostname: redis
    image: redis:latest
    command:
      - --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  celery:
    build: .
    image: celery:latest
    environment:
      - POSTGRES_NAME=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: celery -A myshop worker -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - rabbitmq
      - db
      - redis

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    entrypoint: /entrypoint.sh
    depends_on:
      - db
      - rabbitmq
      - redis

  flower:
    build: .
    image: mher/flower:2.0.1
    command: celery --app myshop flower --broker=amqp://admin:mypass@rabbitmq:5672//
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - celery
      - redis
